### ISSUE TITLE
a few QOL suggestions

### ISSUE THREAD

**Issue by DuckyPolice** [cnlohr/lolra#10]
you should add the ability to use the serial monitor to send messages or hook, say, a pi pico to the esp8266 and send serial data to it which will get transmitted with lora. also add the ability to do other bands such as 433 mhz

**Comment by cnlohr** [comment]
I don't have any specific needs for these features, but, I am happy to help and accept PR's for anyone who wants to write them.

**Comment by DuckyPolice** [comment]
ok, i dont know how to program in what this was programmed in, but the ability to hook a second microcontroller to the esp would be nice for more practical uses as a lora module
